# Configuracoes do Projeto
spring.application.name=Meninas
server.port=8080

# Configuracao do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/Meninas
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123

# Configuracao do Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configuracao de Seguranca (JWT)
jwt.private.key=classpath:chave_privada.pem
jwt.public.key=classpath:chave_publica.pem

# Bootstrap do admin
admin.username=ADMIN
admin.password=meninasOya@2026
